version: '3'

services:
  mailserver:
    image: gomarcd/privacyroot:latest
    container_name: privacyroot
    hostname: mail.privatenode.xyz
    network_mode: host
    restart: always
    environment:
      - DOMAIN=privatenode.xyz
      - CNAME=imap,imaps,smtp,smtps,pop3,pop3s
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./etc/nginx:/etc/nginx
      - ./var/mail:/var/mail
      - ./var/www/privatenode.xyz:/var/www/privatenode.xyz
      - ./etc/opendkim:/etc/opendkim