version: '3'

services:
  mailserver:
    image: gomarcd/privacyroot:latest
    container_name: privacyroot
    # Uncomment to build from Dockerfile instead of downloading remote image
    # build:
    #  context: .
    #  dockerfile: Dockerfile    
    hostname: mail.privatenode.xyz
    #network_mode: host
    restart: always
    # Uncomment if fail2ban enabled
    # cap_add:
    #   - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 110:110
      - 143:143
      - 465:465
      - 587:587
      - 993:993
      - 995:995    
    environment:
    # Uncomment to enable fail2ban
    #  - ENABLE_FAIL2BAN=yes
      - DOMAIN=privatenode.xyz
      - CNAME=imap,imaps,smtp,smtps,pop3,pop3s
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
    #  - ./etc/nginx:/etc/nginx
      - ./var/mail:/var/mail
      - ./var/www/privatenode.xyz:/var/www/privatenode.xyz
      - ./etc/opendkim:/etc/opendkim